-- Seed vocabulary rows (difficulty_level, spanish_word, english_word)
insert into public.questions (difficulty_level, spanish_word, english_word)
values
('A1.1', 'Hola', 'Hello'),
('A1.1', 'Adiós', 'Goodbye'),
('A1.1', 'Gracias', 'Thank you'),
('A1.1', 'Sí', 'Yes'),
('A1.1', 'No', 'No'),
('A1.1', 'Por favor', 'Please'),
('A1.1', 'Buenos días', 'Good morning'),
('A1.1', 'Agua', 'Water'),
('A1.1', 'Uno', 'One'),
('A1.1', 'Amigo', 'Friend (male)'),
('A1.1', 'Gato', 'Cat'),
('A1.1', 'Perro', 'Dog'),
('A1.2', 'Buenas noches', 'Good night'),
('A1.2', 'Perdón', 'Excuse me / Sorry'),
('A1.2', 'Me llamo Ana', 'My name is Ana'),
('A1.2', '¿Cómo estás?', 'How are you?'),
('A1.2', 'Estoy bien', 'I am fine'),
('A1.2', 'Dos', 'Two'),
('A1.2', 'Rojo', 'Red'),
('A1.2', 'Casa', 'House'),
('A1.2', 'Libro', 'Book'),
('A1.2', 'Madre', 'Mother'),
('A1.2', 'Padre', 'Father'),
('A1.2', 'Soy de México', 'I''m from Mexico'),
('A1.3', 'Tengo dos hermanos', 'I have two brothers'),
('A1.3', 'La casa es grande', 'The house is big'),
('A1.3', 'Hablo poco español', 'I speak a little Spanish'),
('A1.3', '¿Qué hora es?', 'What time is it?'),
('A1.3', 'Me gusta el café', 'I like coffee'),
('A1.3', '¿Dónde está el baño?', 'Where is the bathroom?'),
('A1.3', 'Tengo hambre', 'I am hungry'),
('A1.3', 'Hoy es lunes', 'Today is Monday'),
('A1.3', 'Ella es mi hermana', 'She is my sister'),
('A1.3', '¿Cuántos años tienes?', 'How old are you?'),
('A1.3', 'Vivo en un apartamento pequeño', 'I live in a small apartment'),
('A1.3', 'Hace frío hoy', 'It is cold today'),
('A2.1', 'Normalmente me despierto a las 7', 'I usually wake up at 7'),
('A2.1', 'Ella trabaja en un hospital', 'She works in a hospital'),
('A2.1', 'Nosotros nunca comemos carne', 'We never eat meat'),
('A2.1', '¿Te gusta bailar?', 'Do you like to dance?'),
('A2.1', 'Tengo que estudiar esta noche', 'I have to study tonight'),
('A2.1', 'Hay muchas personas', 'There are many people'),
('A2.1', 'Puedo nadar', 'I can swim'),
('A2.1', 'Mi cumpleaños es en mayo', 'My birthday is in May'),
('A2.1', 'Esta camisa es más cara', 'This shirt is more expensive'),
('A2.1', 'Voy al parque', 'I''m going to the park'),
('A2.2', 'Fui al cine ayer', 'I went to the cinema yesterday'),
('A2.2', 'Ella comió mucho', 'She ate a lot'),
('A2.2', 'Compramos un coche nuevo', 'We bought a new car'),
('A2.2', 'Vivieron en España', 'They lived in Spain'),
('A2.2', '¿Qué hiciste?', 'What did you do?'),
('A2.2', 'Todavía no he comido', 'I haven''t eaten yet'),
('A2.2', 'Estaba lloviendo', 'It was raining'),
('A2.2', 'Jugaba al fútbol', 'I played football (used to)'),
('A2.2', 'Llegó a las 8', 'He arrived at 8'),
('A2.2', 'Hemos visitado Madrid', 'We have visited Madrid'),
('A2.3', 'Mañana viajaré', 'Tomorrow I will travel'),
('A2.3', 'Quisiera un café', 'I would like a coffee'),
('A2.3', 'Si llueve, me quedaré en casa', 'If it rains, I''ll stay home'),
('A2.3', 'Dame el libro, por favor', 'Give me the book, please'),
('A2.3', 'Se lo di', 'I gave it to him/her'),
('A2.3', 'No te preocupes', 'Don''t worry'),
('A2.3', 'Debemos salir ahora', 'We must leave now'),
('A2.3', 'Estaba leyendo cuando llamé', 'He was reading when I called'),
('A2.3', 'Este restaurante es el mejor', 'This restaurant is the best'),
('A2.3', 'La conozco desde hace años', 'I have known her for years'),
('B1.1', 'Quiero que vengas', 'I want you to come'),
('B1.1', 'Es importante que escuchemos', 'It''s important we listen'),
('B1.1', 'Dudo que sepa', 'I doubt that he knows'),
('B1.1', 'Cuando llegue, llamaré', 'When I arrive, I''ll call'),
('B1.1', 'Espero que te sientas mejor', 'I hope you feel better'),
('B1.1', 'No abras la puerta', 'Don''t open the door'),
('B1.1', 'Quizá venga', 'Maybe she''ll come'),
('B1.1', 'Es extraño que no esté aquí', 'It''s strange he isn''t here'),
('B1.1', 'Busco a alguien que hable inglés', 'I''m looking for someone who speaks English'),
('B1.1', 'Antes de que te vayas, come algo', 'Before you leave, eat something'),
('B1.2', 'Viajaría si tuviera dinero', 'I would travel if I had money'),
('B1.2', 'Me dijo que estaba cansado', 'He told me he was tired'),
('B1.2', 'Para mañana habré terminado', 'By tomorrow I will have finished'),
('B1.2', 'Ha estado lloviendo todo el día', 'It has been raining all day'),
('B1.2', 'Me preguntó dónde vivía', 'She asked me where I lived'),
('B1.2', 'El libro que leí', 'The book that I read'),
('B1.2', 'Ya había comido', 'I had already eaten'),
('B1.2', 'Es la mejor película que he visto', 'It''s the best film I have seen'),
('B1.2', 'Le pedí que ayudara', 'I asked him to help'),
('B1.2', 'Aunque es rico, no es feliz', 'Although he''s rich, he isn''t happy'),
('B1.3', 'Es necesario actuar ya', 'It''s necessary to act now'),
('B1.3', 'Ojalá pudiera volar', 'I wish I could fly'),
('B1.3', 'En cuanto llegue, comeremos', 'As soon as he arrives, we''ll eat'),
('B1.3', 'Se casaron el verano pasado', 'They got married last summer'),
('B1.3', 'La hago reír', 'I make her laugh'),
('B1.3', 'Me estoy acostumbrando a la ciudad', 'I''m getting used to the city'),
('B1.3', 'Iban a llamar pero no lo hicieron', 'They were going to call but didn''t'),
('B1.3', 'La película me hizo llorar', 'The film made me cry'),
('B1.3', 'Me pregunto dónde estará', 'I wonder where he is'),
('B1.3', 'Deberías haberme llamado', 'You should have called me'),
('B2.1', 'El coche fue comprado por Juan', 'The car was bought by Juan'),
('B2.1', 'Se dice que es rico', 'It is said that he is rich'),
('B2.1', 'Si hubiera sabido, habría venido', 'Had I known, I would have come'),
('B2.1', 'Lo que digas', 'Whatever you say'),
('B2.1', 'Ya va siendo hora de que nos vayamos', 'It''s high time we left'),
('B2.1', 'A pesar de la lluvia, salimos', 'Despite the rain, we went out'),
('B2.1', 'Le hice hacerlo', 'I made him do it'),
('B2.1', 'Debe de haberse ido ya', 'He must have left already'),
('B2.1', 'Conseguimos terminar', 'We managed to finish'),
('B2.1', 'Vale la pena verlo', 'It''s worth seeing'),
('B2.2', 'Por mucho que lo intente', 'No matter how hard he tries'),
('B2.2', 'Actúa como si fuera rico', 'He acts as if he were rich'),
('B2.2', 'Lo mejor sería esperar', 'It would be best to wait'),
('B2.2', 'Lo hice arreglar', 'I had it fixed'),
('B2.2', 'Lo que me sorprende es el silencio', 'What surprises me is the silence'),
('B2.2', 'Niega haberlo dicho', 'He denies having said it'),
('B2.2', 'Con tal de que estudies', 'Provided that you study'),
('B2.2', 'Tengo muchas ganas de verte', 'I look forward to seeing you'),
('B2.2', 'No es que no me guste', 'It''s not that I don''t like it'),
('B2.2', 'Logró que hablara', 'She got me to talk'),
('B2.3', 'De no ser por ti, estaría perdido', 'Were it not for you, I''d be lost'),
('B2.3', 'Se dice que es un genio', 'He is said to be a genius'),
('B2.3', 'No puedo evitar reírme', 'I can''t help laughing'),
('B2.3', 'En cuanto hubo terminado', 'As soon as he had finished'),
('B2.3', 'Quien gane se lleva el premio', 'Whoever wins gets the prize'),
('B2.3', 'Ya es hora de que sepas la verdad', 'It''s about time you knew the truth'),
('B2.3', 'Insiste en pagar', 'He insists on paying'),
('B2.3', 'Apenas había llegado cuando…', 'Hardly had I arrived when…'),
('B2.3', 'Hace como que no entiende', 'He pretends not to understand'),
('B2.3', 'Parece poco probable que venga', 'It seems unlikely she''ll come'),
('C1.1', 'No sea que se te olvide', 'Lest you forget'),
('C1.1', 'Lejos de mí criticar', 'Far be it from me to criticize'),
('C1.1', 'Pase lo que pase', 'Come what may'),
('C1.1', 'Le salió el tiro por la culata', 'It backfired on him'),
('C1.1', 'Andarse por las ramas', 'To beat about the bush'),
('C1.1', 'En un abrir y cerrar de ojos', 'In the blink of an eye'),
('C1.1', 'La gota que colmó el vaso', 'The straw that broke the camel''s back'),
('C1.1', 'Mordió el polvo', 'He bit the dust'),
('C1.1', 'De Pascuas a Ramos', 'Once in a blue moon'),
('C1.1', 'Tomar con pinzas', 'To take with a grain of salt'),
('C1.2', 'Estaba a punto de irse', 'He was about to leave'),
('C1.2', 'Pensándolo bien', 'On second thought'),
('C1.2', 'Me retracto', 'I take it back'),
('C1.2', 'Así de pronto', 'Off the top of my head'),
('C1.2', 'Vale su peso en oro', 'Worth its weight in gold'),
('C1.2', 'Meter la pata', 'To put one''s foot in it'),
('C1.2', 'A la mínima', 'At the drop of a hat'),
('C1.2', 'Del dicho al hecho hay mucho trecho', 'Easier said than done'),
('C1.2', 'Llover a cántaros', 'To rain cats and dogs'),
('C1.2', 'Echarse atrás', 'To get cold feet'),
('C1.3', 'Hacer la vista gorda', 'To turn a blind eye'),
('C1.3', 'Matar dos pájaros de un tiro', 'To kill two birds with one stone'),
('C1.3', 'Es pan comido', 'It''s a piece of cake'),
('C1.3', 'Hablando del rey de Roma', 'Speak of the devil'),
('C1.3', 'Estar en el séptimo cielo', 'To be on cloud nine'),
('C1.3', 'Costar un ojo de la cara', 'To cost an arm and a leg'),
('C1.3', 'Irse de la lengua', 'To spill the beans'),
('C1.3', 'Apretar los dientes', 'To bite the bullet'),
('C1.3', 'Dar en el clavo', 'To hit the nail on the head'),
('C1.3', 'Quemarse las pestañas', 'To burn the midnight oil'),
('C2.1', 'Tirar la toalla', 'To throw in the towel'),
('C2.1', 'Tomar el pelo', 'To pull someone''s leg'),
('C2.1', 'Consultarlo con la almohada', 'To sleep on it'),
('C2.1', 'No hay mal que por bien no venga', 'A blessing in disguise'),
('C2.1', 'Por los pelos', 'By the skin of one''s teeth'),
('C2.1', 'Hacer lo imposible', 'To bend over backwards'),
('C2.1', 'Al pan, pan y al vino, vino', 'To call a spade a spade'),
('C2.1', 'Desahogarse', 'To get something off one''s chest'),
('C2.1', 'En el calor del momento', 'In the heat of the moment'),
('C2.1', 'Enterrar el hacha de guerra', 'To bury the hatchet'),
('C2.2', 'Hacer de abogado del diablo', 'To play devil''s advocate'),
('C2.2', 'Una tormenta en un vaso de agua', 'A storm in a teacup'),
('C2.2', 'Llevar el corazón en la mano', 'To wear one''s heart on one''s sleeve'),
('C2.2', 'Dormirse en los laureles', 'To rest on one''s laurels'),
('C2.2', 'Coger el toro por los cuernos', 'Take the bull by the horns'),
('C2.2', 'Para colmo de males', 'To add insult to injury'),
('C2.2', 'Un lobo con piel de cordero', 'A wolf in sheep''s clothing'),
('C2.2', 'Meterse en un laberinto sin fin', 'To go down a rabbit hole'),
('C2.2', 'Le dijo la sartén al cazo', 'The pot calling the kettle black'),
('C2.2', 'Irse de juerga', 'To paint the town red'),
('C2.3', 'Genio y figura hasta la sepultura', 'A leopard cannot change its spots'),
('C2.3', 'Cortar por lo sano', 'To cut the Gordian knot'),
('C2.3', 'Encontrar la horma de su zapato', 'To meet one''s Waterloo'),
('C2.3', 'Sobrar adornos', 'To gild the lily'),
('C2.3', 'Una victoria pírrica', 'A Pyrrhic victory'),
('C2.3', 'Echar margaritas a los cerdos', 'To cast pearls before swine'),
('C2.3', 'Regodearse en la desgracia ajena', 'Schadenfreude'),
('C2.3', 'Hilar muy fino', 'To split hairs'),
('C2.3', 'Como pez fuera del agua', 'Like a fish out of water'),
('C2.3', 'Hacer un esfuerzo adicional', 'To go the extra mile')
on conflict (difficulty_level, spanish_word)
do update set english_word = excluded.english_word;
