create table if not exists public.questions (
  id bigint generated by default as identity primary key,
  difficulty_level text not null,
  spanish_word text not null,
  english_word text not null,
  created_at timestamptz not null default now(),
  constraint questions_difficulty_level_not_blank check (btrim(difficulty_level) <> ''),
  constraint questions_spanish_word_not_blank check (btrim(spanish_word) <> ''),
  constraint questions_english_word_not_blank check (btrim(english_word) <> '')
);

create index if not exists questions_difficulty_level_idx on public.questions (difficulty_level);

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'questions_difficulty_spanish_unique'
      and conrelid = 'public.questions'::regclass
  ) then
    alter table public.questions
      add constraint questions_difficulty_spanish_unique unique (difficulty_level, spanish_word);
  end if;
end
$$;

alter table public.questions enable row level security;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'questions'
      and policyname = 'authenticated users can read questions'
  ) then
    create policy "authenticated users can read questions"
    on public.questions
    for select
    to authenticated
    using (true);
  end if;
end
$$;
